import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', 
    pathMatch: 'full', 
    loadComponent: () => import('./landing/landing.component').then(m => m.LandingComponent) },
  { path: 'dashboard', 
    pathMatch: 'full', 
    loadComponent: () => import('./dashboard/dashboard.component').then(m => m.DashboardComponent) },
  { path: 'lesson-1', 
    pathMatch: 'full', 
    loadComponent: () => import('./alphabets-lesson/alphabets-lesson.component').then(m => m.AlphabetsLessonComponent) },
  { path: 'practise-1', 
    pathMatch: 'full', 
    loadComponent: () => import('./alphabets-practise/alphabets-practise.component').then(m => m.AlphabetsPractiseComponent) },
  { path: 'lesson-3', 
    pathMatch: 'full', 
    loadComponent: () => import('./lesson-3/lesson-3.component').then(m => m.Lesson3Component) },
  { path: 'practise-3', 
    pathMatch: 'full', 
    loadComponent: () => import('./practise-3/practise-3.component').then(m => m.UrduPracticeSheetComponent) },
  { path: 'lesson-2', 
    pathMatch: 'full', 
    loadComponent: () => import('./lesson-2/lesson-2.component').then(m => m.Lesson2Component) },
  { path: 'practise-2', 
    pathMatch: 'full', 
    loadComponent: () => import('./practise-2/practise-2.component').then(m => m.PronunciationPracticeComponent) },
  { path: 'community', 
    pathMatch: 'full', 
    loadComponent: () => import('./community/community.component').then(m => m.CommunityComponent) },
  { path: 'daily-challenge', 
    pathMatch: 'full', 
    loadComponent: () => import('./daily-challenge/daily-challenge.component').then(m => m.DailyChallengeComponent) },
  { path: 'lesson-4', 
    pathMatch: 'full', 
    loadComponent: () => import('./lesson-4/lesson-4.component').then(m => m.ConversationLessonComponent) }

];